apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/hendrikmaus/argo-cd-app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated: {}
